img_tags={
	"0":"You are in main lobby, slightly right to lift,approximately 2 meter infront of Amarnath and sashi khosla office facing office entry.",
	"1":"You are in in left region to lift,approximately 3 meter infront of Room number 118 named PA room.",
	"2":"You are in in left region to lift,approximately 1.5 meter slight right of Room number 116 .",
	"3":"You are in left region to lift,approximately 1.5 meter infront of Room number 116 ",
	"4":"You are in left region to lift,5 to 6 meter from room number 118 facing PA room.",
	"5":"You are in left region to lift,6 to 7 meter from room number 118 facing PA room.",
	"6":"You are in left region to lift,7 to 8 meter from room number 118 facing PA room.",
	"7":"You are in left region to lift,near main lobby,8 to 9 meter from room number 118 facing PA room.",
	"8":"You are in left region to lift,main lobby,1 to 2 meter left to room number 115 name Manik Varma,ICTD lab on the right , you are facing exit.",
	"9":"You are in left region to lift,in the lobby,main lobby,5 to 6 meter away from the exit infront.",
	"10":"You are in left region to lift,main lobby,1 to 2 meter infront of room number 115 named manik varma.",
	"11":"You are in left region to lift,main lobby,1 to 2 meter infront of ICTD lab facing it.",
	"12":"You are in left region to lift,main lobby,2 to 3 meter away from exit door infront.",
	"13":"You are in left region to lift,main lobby,1 to 2 meter away from exit door infront.",
	"14":"You are in left region to lift,main lobby,approximately 1 to 2 meter from exit and facing fire hoze reel.",
	"15":"You are in left region to lift,main lobby,2 to 3 meter right to the ICTD lab,facing cupboards.",
	"16":"You are in left region to lift,main lobby,slightly left of committee room,facing cupboards.",
	"17":"You are in left region to lift,main lobby,committee room on the right turn.",
	"18":"You are in left region to lift,main lobby,1 to 2 meter infront of committee room.",
	"19":"You are in left region to lift,main lobby,2 to 3 meter infront of committee room.",
	"20":"You are slight left to the lift in the main lobby ,near lobby door.",
	"21":"You are 1.5 to 2.5 meter infront of lift with lift button on left.",
	"22":"You are 1 to 2 meter infront of lift.",
	"23":"You are 2 to 3 meter from lift with lift button on right.",
	"24":"You are 1 to 2 meter from lift with lift button on right.",
	"25":"You are 1 to 2 meter facing away from lift .",
	"26":"You are in right region to lift,main lobby,Amarnath and Sashi khosla office approximately 2 meters on the right turn .",
	"27":"You are in right region to lift,main lobby,1 to 2 meters infront of Amarnath and Sashi khosla office facing it.",
	"28":"You are in right region to lift,main lobby,2 to 3 meters infront of Amarnath and Sashi khosla office facing it.",
	"29":"You are in right region to lift,main lobby,a lobby starting on left turn,2 to 3 meters from room 106 behind.",
	"30":"You are in right region to lift,main lobby,10 to 12 meters from the exit door infront.",
	"31":"You are 5 to 6 meters from the exit door infront , near watercooler.",
	"32":"You are 1 to 2 meters from the exit door infront.",
	"33":"You are 2 to 3 meters fron the boys washroom infront ,exit door on the slight left turn.",
	"34":"You are 1 to 2 meters from the drinking water cooler infront.",
	"35":"You are 1 to 2 meters from the ladies washroom infront.",
	"36":"You are in right region of the lift,1 to 2 meters infront of room number 103 named Aaditeshwar seth.",
	"37":"You are in right region of the lift,2 to 3 meters infront of ladies washroom facing it.",
	"38":"You are in right region of the lift,near main lobby end,2 to 3 meters slight right to the ladies washroom facing fire extinguishers.",
	"39":"You are in right region of the lift,near main lobby end,2 to 3 meters slight left to room number 106 facing it.",
	"40":"You are in right region of the lift,near main lobby end,2 to 3 meters infront of room number 106 facing it.",
	"41":"You are in right region of the lift,near main lobby end,2 to 3 meters slight left to room number 104 named Rahul Garg facing it.",
	"42":"You are in right region of the lift,1 to 2 meters infront of room number 104 named Rahul Garg facing it.",
	"43":"You are in right region of the lift,2 to 3 meters slight right to room number 104 named Rahul Garg facing it.",
	"44":"You are in right region of the lift,room number 103 named Aaditeshwar seth 2 to 3 meters on left turn,facing room 102.",
	"45":"You are in right region of the lift,1 to 2 meters infront of room number 102 named Kolin Paul facing it.",
	"46":"You are in right region of the lift,room number 103 named Aaditeshwar seth 2 to 3 meters on the right turn.",
	"47":"You are in right region of the lift,facing towards the hall,room number 103 named Aaditeshwar seth behind .",
	"48":"You are in right region of the lift,near main lobby end,a lobby starting infront,room number 105 is 2 to 3 meters on left turn.",
	"49":"You are in left region of the lift,3 to 4 meters infront of room number 118 named PA room facing it.",
	"50":"You are in left region of the lift,room number 118 named PA room is 3 to 4 meters on the right turn ,you are facing hall.",
	"51":"You are in left region of the lift,8 to 9 meters infront of PA room facing it.",
	"52":"You are in left region of the lift,near main lobby end,facing hall.",
	"53":"You are in left region of the lift,in the main lobby,cupboards 1 to 2 meters behind,exit door 4 to 5 meters.",
	"54":"You are in left region of the lift,in the main lobby,ICTD lab on right turn,8 to 9 meters from the exit door infront.",
	"55":"You are in left region of the lift,in the main lobby,4 to 5 meters from the exit door infront.",
	"56":"You are in left region of the lift,in the main lobby,3 to 4 meters from room number 115 named Manik Varma facing it.",
	"57":"You are in left region of the lift,in the main lobby,3 to 4 meters infront of the ICTD lab facing it.",
	"58":"You are in left region of the lift,in the main lobby,ICTD lab is 3 to 4 meters on slight left turn,facing committee room.",
	"59":"You are in left region of the lift,in the main lobby,1 to 2 meters slight left of committee room facing it.",
	"60":"You are in the lobby,near lift on 1 to 2 meters right turn.",
	"61":"You are 1 to 2 meters facing away from the lift.",
	"62":"You are 1 to 2 meters facing away from the lift.",
	"63":"You are 2 to 3 meters infront of the lift facing it with lift buttons on the left.",
	"64":"You are in the main lobby,lift is 1 to 2 meters on right turn.",
	"65":"You are in right region of the lift,in the main lobby,office on left turn,8 to 9 meters from room number 105.",
	"66":"You are in right region of the lift,in the main lobby,2 to 3 meters infront of Amarnath and sashi khosla office facing it.",
	"67":"You are in right region of the lift,near main lobby end,facing exit door 10 to 12 meters away.",
	"68":"You are in right region of the lift,near main lobby end,facing room number 105 4 to 5 meters away.",
	"69":"You are in right region of the lift ,exit door is 4 to 5 meters infront and drinking water cooler on right turn.",
	"70":"You are in right region of the lift ,4 to 5 meters slightely right to the drinking watercooler facing it.",
	"71":"You are in right region of the lift ,near main lobby end,10 to 12 meters from room number 101 facing it.",
	"72":"You are in right region of the lift ,room number 104 named Rahul garg on left turn,7 to 8 meters from room number 101 facing it.",
	"73":"You are in right region of the lift,2 to 3 meters infront of room number 104 named Rahul garg facing it.",
	"74":"You are in right region of the lift ,near main lobby end,3 to 4 meters left to room number 104 named Rahul Garg facing it.",
	"75":"You are in right region of the lift ,in the main lobby,2 to 3 meters infront of Amarnath and Sashikhosla office facing it.",
	"76":"You are in right region of the lift ,in the main lobby,Amarnath and Sashikhosla office 1 to 2 meters behind ,facing hall.",
	"77":"You are in right region of the lift ,in the main lobby,5 to 6 meters from room 105 behind.",
	"78":"You are in the main lobby,lift is 1 to 2 meters on left turn.",
	"79":"You are in the main lobby,lift is 1 to 2 meters on left turn.",
	"80":"You are in left region of the lift,in the main lobby,4 to 5 meters slight right to the ICTD lab facing committee room .",
	"81":"You are in the main lobby,3 to 4 meters from the lift on the right turn.",
	"82":"You are in right region of the lift,near ladies washroom facing away from it.",
	"83":"You are in right region of the lift,near ladies washroom facing away from it.",
	"84":"You are in right region of the lift,room number 104 named Rahul garg is 2 to 3 meters on right turn .",
	"85":"You are in right region of the lift,room number 104 named Rahul garg is 1 to 2 meters on right turn .",
	"86":"You are in left region of the lift,in the main lobby,5 to 6 meters diagonally left to room number 116 named Manik varma.",
	"87":"You are in left region of the lift,in the main lobby,2 to 3 meters diagonally left to the committee room.",
	"88":"You are in left region of the lift,in the main lobby,committee room is 1 to 2 meters on left turn.",
	"89":"You are in right region of the lift, near main lobby end,3 to 4 meters from fire extinguishers near ladies washroom facing it .",
	"90":"You are in right region of the lift,watercooler is 2 to 3 meters on left turn,facing ladies washroom.",
	"91":"You are in right region of the lift,3 to 4 meters diagonally left to the drinking watercooler facing it.",
	"92":"You are in right region of the lift,1 to 2 meters infront of room number 107 near boys washroom.",
	"93":"You are in right region of the lift, 2 to 3 meters diagonally left of the boys washroom facing it.",
	"94":"You are in right region of the lift,near exit door ,1 to 2 meters away from stairs infront.",
	"95":"You are in right region of the lift,3 to 4 meters from exit door facing it.",
	"96":"You are in right region of the lift,3 to 4 meters from fire hose reel,near exit door on right turn.",
	"97":"You are in right region of the lift,near room 104 named Rahul garg,facing hall.",
	"98":"You are in right region of the lift,in the main lobby,Office is 1 meter on left turn.",
	"99":"You are in right region of the lift,in the main lobby,facing away from the Amarnath and sashi khosla office.",
	"100":"You are in right region of the lift,in the main lobby,facing away from the Amarnath and sashi khosla office.",
	"101":"You are in right region of the lift,near main lobby end,3 to 4 meters diagonally right to office facing it.",
	"102":"you are in front of the comittee room facing towards lift at a distance of around 4 metres from it",
	"103":"You are standing in front of the lift and lift is on your right",
	"104":"You are in front of the lift facing away from it.",
	"105":"you are in the right region of lift and at a distance of around 5 metre from washroom standing infront of it",
	"106":"you are standing in front of washroom area at a distance of around 5 metre from it facing it",
	"107":"you are in the right region of the lift facing towards the lift at around 3 metre from it",
	"108":"You are standing right infront of the lift and the lift is on your left"
	}
